---
# tasks file for nodejs.dev
- name: Install nodejs
  apt:
    name: nodejs
    update_cache: yes
    state: latest

- name: Install npm
  apt:
    name: npm
    state: latest

- name: Install pm2
  npm:
    name: pm2
    global: yes
    state: latest

- name: Add Group 'memberid'
  group:
    name: memberid
    system: yes
    state: present

- name: Add User 'memberid'
  user:
    name: memberid
    createhome: no
    shell: /usr/sbin/nologin
    group: memberid
    system: yes

- name: Make Directory for Nodejs App
  file:
    path: /var/www/nodejs
    state: directory
    mode: 0755
    owner: memberid
    group: memberid

- name: change dir to /var/www/nodejs
  shell: ls
  args:
    chdir: /var/www/nodejs

- name: Git clone repo
  command: git clone https://github.com/stevenstevanus/testnodejs.git   
